
//import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.Timer;

/**
 *
 * @author Pankaj Yadav
 */
public class Logins extends javax.swing.JFrame {

    Timer tm;
    int x;
    String[] list = {   "C:/images/b1.png",
                        "C:/images/b3.jpg",
                        "C:/images/b4.jpg",
                        "C:/images/b5.jpg"
                        };

    /**
     * Creates new form AddNewBook
     */
    public Logins() {
        initComponents();
        
         
        //this.setUndecorated(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        
            //This for on enter key function//login
        btnLogin.registerKeyboardAction(btnLogin.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, false)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false),
                                      JComponent.WHEN_IN_FOCUSED_WINDOW);
 
        btnLogin.registerKeyboardAction(btnLogin.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, true)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true),
                                      JComponent.WHEN_IN_FOCUSED_WINDOW);
        
         jpass1.setEchoChar((char)0);
         
                    juser1.disable();
                    jpass1.disable(); 
       // SetImageSize(6);
        
        tm = new Timer(5000, new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                    
                    SetImageSize(x);
                    x +=1;
                    if(x >= list.length){
                        
                        x = 0;
                    }
                }
        
            });
        tm.start();
        
          try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433; database=Trinity_DB; user=sa; password=Tunani14real;";
            Connection connect = DriverManager.getConnection(url);
            Statement st = connect.createStatement();
            ResultSet rs = st.executeQuery("select * from Role_Table");
            
           while(rs.next()){
               
               drpRole.addItem(rs.getString("Role_Name"));
               
           }
           connect.close();
           
        }catch(Exception Error){
            
               JOptionPane.showMessageDialog(null, Error);
        }
        
        
    }
    
     
    public void SetImageSize(int i){
        ImageIcon icon =new ImageIcon(list[i]);
        Image img = icon.getImage();
        Image newImg = img.getScaledInstance(lblSlide_Login.getWidth(), lblSlide_Login.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImc = new ImageIcon(newImg);
        lblSlide_Login.setIcon(newImc);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblSlide_Login = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jpass1 = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        drpRole = new javax.swing.JComboBox<>();
        juser1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(847, 462));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel4.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Trinity University Library Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 640, 40));

        lblSlide_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSlide_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmain.png"))); // NOI18N
        jPanel1.add(lblSlide_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 430, 360));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_img.jpg"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pass_img.png"))); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jpass1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jpass1.setText("Enter password");
        jpass1.setEnabled(false);
        jpass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpass1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpass1FocusLost(evt);
            }
        });
        jpass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpass1MouseClicked(evt);
            }
        });
        jPanel6.add(jpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 240, 40));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        btnLogin.setBackground(new java.awt.Color(0, 51, 102));
        btnLogin.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 85, 36));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOGIN");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 180, 30));

        drpRole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        drpRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- select user --" }));
        drpRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpRoleActionPerformed(evt);
            }
        });
        jPanel3.add(drpRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 220, 30));

        juser1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        juser1.setForeground(new java.awt.Color(102, 102, 102));
        juser1.setText("Enter username");
        juser1.setEnabled(false);
        juser1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                juser1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                juser1FocusLost(evt);
            }
        });
        juser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                juser1MouseClicked(evt);
            }
        });
        jPanel3.add(juser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 240, 40));

        jLabel2.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User : ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 60, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 340, 300));

        jLabel8.setBackground(new java.awt.Color(0, 204, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 150, 80));

        jLabel1.setFont(new java.awt.Font("Segoe Condensed", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Designed by Ayejafo Tunde");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 130, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
       try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433; database=Trinity_DB; user=sa; password=Tunani14real;";
            Connection connect = DriverManager.getConnection(url);
            String sql = "select * from Login_vw_Table where Username = ? and Password = ?";
            String sql2 = "select * from User_vw_Table where User_Name = ? and Password = ?";
            PreparedStatement pst = connect.prepareStatement(sql);
            PreparedStatement pst2 = connect.prepareStatement(sql2);

            //pst.setString(1, Name);
            pst.setString(1, juser1.getText());
            pst.setString(2, jpass1.getText());
            
            ResultSet rs = pst.executeQuery();
            
            pst2.setString(1, juser1.getText());
            pst2.setString(2, jpass1.getText());
            ResultSet rs2 = pst2.executeQuery();

            if(rs.next()){
                if(juser1.getText().equals(rs.getString("Username")) && drpRole.getSelectedItem().equals(rs.getString("Role_Name"))){
                    String get = rs.getString("Username");
                    JOptionPane.showMessageDialog(null,  "Sucessful Login!!!", "Sucess", JOptionPane.INFORMATION_MESSAGE);
                    juser1.setText("");
                    jpass1.setText("");

                    MainLayer home = new MainLayer();
                    MainLayer.F_user.setText(get);
                    home.setVisible(true);
                    this.dispose();
                }
            else{

                JOptionPane.showMessageDialog(null,  "incorrect username or password", "Failed", JOptionPane.INFORMATION_MESSAGE);

                juser1.setText("Enter username");
                jpass1.setText("Enter password");

            }
                
            }else if(rs2.next()){
                if(juser1.getText().equals(rs2.getString("User_Name")) && drpRole.getSelectedItem().equals(rs2.getString("Role_Name"))){
                    String get2 = rs2.getString("User_Name");
                    JOptionPane.showMessageDialog(null,  "Sucessful Login!!!", "Sucess", JOptionPane.INFORMATION_MESSAGE);
                    
                    juser1.setText("");
                    jpass1.setText("");

                    BookDetails home = new BookDetails();
                    BookDetails.F_user.setText("Hi! " + get2);
                    BookDetails.F_user2.setVisible(false);
                    BookDetails.F_user4.setVisible(false);
                    BookDetails.lblDel.setVisible(false);
                    BookDetails.lblUpdate.setVisible(false);
                    BookDetails.lblFrom.setVisible(false);
                    BookDetails.lblTo.setVisible(false);
                    BookDetails.dcFrom.setVisible(false);
                    BookDetails.dcTo.setVisible(false);
                    BookDetails.btnGEN.setVisible(false);
                    BookDetails.btnExport.setVisible(false);
                    BookDetails.btnFilter1.setVisible(false);
                    BookDetails.lblLG.setVisible(true);
                    BookDetails.jButton1.setVisible(false);
                   
                    home.setVisible(true);
                    this.dispose();
                }
            else{

                JOptionPane.showMessageDialog(null,  "incorrect username or password", "Failed", JOptionPane.INFORMATION_MESSAGE);

                juser1.setText("Enter username");
                jpass1.setText("Enter password");

            }
            
            }
            else{

                JOptionPane.showMessageDialog(null,  "incorrect username or password", "Failed", JOptionPane.INFORMATION_MESSAGE);

                juser1.setText("Enter username");
                jpass1.setText("Enter password");

            }

             connect.close();
             
        }catch(Exception error){

            JOptionPane.showMessageDialog(null, error);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void juser1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_juser1FocusGained
        // TODO add your handling code here:
        
        if(juser1.getText().equals("Enter username")){
            juser1.setText("");
        }
        juser1.setForeground(Color.BLACK);
         juser1.setFont(new Font("TimesRoman", Font.PLAIN, 14)); 
    }//GEN-LAST:event_juser1FocusGained

    private void juser1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_juser1FocusLost
        // TODO add your handling code here:
           if(juser1.getText().equals("")){
            juser1.setText("Enter username");
        }
        
    }//GEN-LAST:event_juser1FocusLost

    private void jpass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpass1FocusGained
        // TODO add your handling code here:
        //jpass1.setText("");
         if( jpass1.getText().equals("Enter password")){
             jpass1.setText("");
        }
         jpass1.setForeground(Color.BLACK);
         jpass1.setFont(new Font("TimesRoman", Font.PLAIN, 14)); 
         
         jpass1.setEchoChar('*');
    }//GEN-LAST:event_jpass1FocusGained

    private void jpass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpass1FocusLost
        // TODO add your handling code here:
           if( jpass1.getText().equals("")){
             jpass1.setText("Enter password");
        }
        
    }//GEN-LAST:event_jpass1FocusLost

    private void drpRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpRoleActionPerformed
        // TODO add your handling code here:
        
        if(drpRole.getSelectedItem().equals("-- select user --")){
            
                    juser1.disable();
                    jpass1.disable();
                    
                    juser1.setText("Enter Username");
                    jpass1.setText("Enter Password");
                    jpass1.setEchoChar((char) 0);
                    JOptionPane.showMessageDialog(null,  "You are not recognised as a user!", "Failed", JOptionPane.INFORMATION_MESSAGE);
                   
        
        }else{
              juser1.enable();
              jpass1.enable(); 
              jpass1.setEchoChar((char) 0);
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433; database=Trinity_DB; user=sa; password=Tunani14real;";
            Connection connect = DriverManager.getConnection(url);
            String sql = "select * from Role_Table where Role_Name = ?";
            PreparedStatement pst = connect.prepareStatement(sql);

            pst.setString(1, String.valueOf(drpRole.getSelectedItem()));

            ResultSet rs = pst.executeQuery();

           // drpSubject.removeAllItems();
            while(rs.next()){

                //drpSubject.addItem(rs.getString("Subject"));
                 if(drpRole.getSelectedItem().equals("Students")){
                     
         //jpass1.setEchoChar((char) 0);
                    
                    
                    juser1.setText("Enter Username");
                    jpass1.setText("Enter Password");
                 
                 }
                 
                else if(drpRole.getSelectedItem().equals("Librarian")){
                        
                    juser1.setText("Enter Username");
                    jpass1.setText("Enter Password");
                    
                        }
                else
                    {          
                    }
                 
            }
            connect.close();

        }catch(Exception Error){

            JOptionPane.showMessageDialog(null, Error);
        }
        
        }
    }//GEN-LAST:event_drpRoleActionPerformed

    private void juser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juser1MouseClicked
        // TODO add your handling code here:
        
                    juser1.setText("");
                    //jpass1.setText("");
    }//GEN-LAST:event_juser1MouseClicked

    private void jpass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpass1MouseClicked
        // TODO add your handling code here:
        
                    //juser1.setText("");
                    jpass1.setText("");
    }//GEN-LAST:event_jpass1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logins().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> drpRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jpass1;
    private javax.swing.JTextField juser1;
    private javax.swing.JLabel lblSlide_Login;
    // End of variables declaration//GEN-END:variables
}
